# Notebook 1.1 - Tensor 
## Basic data structure in PyTorch

The purpose of this notebook is to:
* understand tensor structure
* know how to indexing and operating on tensors
* know hot to moving computation on GPU

Tensor is multidimensionall array

## Installation of required packages

Run only if pytorch hasn't been installed yet.

In [ ]:
! pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

## Why we need tensors
Flow of tensors through deep neural network
<img src="./figures/data_flow_1.PNG" alt="data_flow_1.PNG" width="750">

Operations
<img src="./figures/data_flow_2.PNG" alt="data_flow_2.PNG" width="750">

Multiple operations
<img src="./figures/data_flow_3.PNG" alt="data_flow_3.PNG" width="750">

In PyTorch, **a tensor is a multidimensional array**, very similar to numpy array, but it can run on GPU.

In math and physics the meaning of the term is much wider, it is an algebraic object describing a multilinear relationship between sets of algebraic objects related to a vector space. 

## Let's start

Import PyThorch packet and check version

In [118]:
import torch
torch.version.__version__

'1.10.2+cu102'

## Tensor dimensionality
<img src="./figures/tensor_dimension.PNG" alt="tensor_dimension.PNG" width="350">

Let's construct a few tensors, get their dimensions and shapes/sizes.

In [119]:
s = torch.tensor(2)
print(s)
print('Dimension is {}, and size is {}'.format(s.dim(), s.shape))

tensor(2)
Dimension is 0, and size is torch.Size([])


In [120]:
v = torch.tensor([3, 0, 1])
print(v)
print('Dimension is {}, and size is {}'.format(v.dim(), v.shape))

tensor([3, 0, 1])
Dimension is 1, and size is torch.Size([3])


In [121]:
m = torch.tensor([[1, 0, 2, 0], [1, 7, 2, 2], [9, 5, 9, 4]])
print(m)
print('Dimension is {}, and size is {}'.format(m.dim(), m.shape))

tensor([[1, 0, 2, 0],
        [1, 7, 2, 2],
        [9, 5, 9, 4]])
Dimension is 2, and size is torch.Size([3, 4])


In [122]:
t = torch.tensor([[[0, 6, 4, 2], [5, 3, 8, 2], [7, 3, 1, 1]],[[3, 8, 1, 6], [3, 6, 4, 7], [2, 3, 1, 1]],[[1, 0, 2, 0], [1, 7, 2, 2], [9, 5, 9, 4]]], dtype=torch.float32)
print(t)
print('Dimension is {}, and size is {}'.format(t.dim(), t.size()))

tensor([[[0., 6., 4., 2.],
         [5., 3., 8., 2.],
         [7., 3., 1., 1.]],

        [[3., 8., 1., 6.],
         [3., 6., 4., 7.],
         [2., 3., 1., 1.]],

        [[1., 0., 2., 0.],
         [1., 7., 2., 2.],
         [9., 5., 9., 4.]]])
Dimension is 3, and size is torch.Size([3, 3, 4])


In [123]:
t2 = torch.tensor([[[[1111, 112],[121,122],[131,132]],
  [[1211, 112],[221,122],[231,132]], 
  [[1311, 312],[321,322],[331,332]],
  [[1411, 412],[421,322],[431,432]]],
 [[[2111, 112],[121,122],[131,132]],
  [[2211, 112],[221,122],[231,132]], 
  [[2311, 312],[321,322],[331,332]],
  [[2411, 412],[421,322],[431,432]]],
 [[[3111, 112],[121,122],[131,132]],
  [[3211, 112],[221,122],[231,132]], 
  [[3311, 312],[321,322],[331,332]],
  [[3411, 412],[421,322],[431,432]]],
 [[[4111, 112],[121,122],[131,132]],
  [[4211, 112],[221,122],[231,132]], 
  [[4311, 312],[321,322],[331,332]],
  [[4411, 412],[421,322],[431,432]]],
 [[[5111, 112],[121,122],[131,132]],
  [[5211, 112],[221,122],[231,132]], 
  [[5311, 312],[321,322],[331,332]],
  [[5411, 412],[421,322],[431,432]]]], names=["N", "C", "H", "W"])
print(t2)
print('Dimension is {}, and size is {}'.format(t2.dim(), t2.size()))

tensor([[[[1111,  112],
          [ 121,  122],
          [ 131,  132]],

         [[1211,  112],
          [ 221,  122],
          [ 231,  132]],

         [[1311,  312],
          [ 321,  322],
          [ 331,  332]],

         [[1411,  412],
          [ 421,  322],
          [ 431,  432]]],


        [[[2111,  112],
          [ 121,  122],
          [ 131,  132]],

         [[2211,  112],
          [ 221,  122],
          [ 231,  132]],

         [[2311,  312],
          [ 321,  322],
          [ 331,  332]],

         [[2411,  412],
          [ 421,  322],
          [ 431,  432]]],


        [[[3111,  112],
          [ 121,  122],
          [ 131,  132]],

         [[3211,  112],
          [ 221,  122],
          [ 231,  132]],

         [[3311,  312],
          [ 321,  322],
          [ 331,  332]],

         [[3411,  412],
          [ 421,  322],
          [ 431,  432]]],


        [[[4111,  112],
          [ 121,  122],
          [ 131,  132]],

         [[4211,  112],
        

## Tensor elements types
Possbile tensor elements are Boolean (torch.bool) and the followign numeric types:
<img src="./figures/data_types.PNG" alt="data_types.PNG" width="400">

## Indexing tensor
Zero dimensional tensors cannot be indexed

In [124]:
print(type(s))
print(s)
print(int(s))
s[0]

<class 'torch.Tensor'>
tensor(2)
2


IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

In [ ]:
print(type(v))
print(v)
print(int(v[0]))
int(v)

Lets get 1st row and 2nd column of matrix m

In [ ]:
r1 = m[0]
c2 = m[:,1]
print("m = \n {}".format(m))
print("r1 = \n {}".format(r1))
print("c2 = \n {}".format(c2))

In [ ]:
r1[:] = torch.tensor([8, 9, 7, 9])
c2[1] = 100
print("m = \n {}".format(m))
print("r1 = \n {}".format(r1))
print("c2 = \n {}".format(c2))

Assign operator "=" **returns a reference** (pointing to the same location in memory)

In [ ]:
r1 = torch.tensor([1, 0, 2, 0])
c2[1] = 7
print("m = \n {}".format(m))
print("r1 = \n {}".format(r1))
print("c2 = \n {}".format(c2))

In [ ]:
m[0] = torch.tensor([1, 0, 2, 0])
r1[-1] = 100
print("m = \n {}".format(m))
print("r1 = \n {}".format(r1))
print("c2 = \n {}".format(c2))

What to do if we don't want pointers on existing values

In [ ]:
r1 = m[0].clone()
c2 = m[:,1].clone()
print("m = \n {}".format(m))
print("r1 = \n {}".format(r1))
print("c2 = \n {}".format(c2))
r1[:] = torch.tensor([8, 9, 7, 9])
c2[1] = 100
print("\nAfter the change")
print("m = \n {}".format(m))
print("r1 = \n {}".format(r1))
print("c2 = \n {}".format(c2))

In [ ]:
print("t2 = \n {}".format(t2))
print("t2[:,:,:,0] = \n {}".format(t2[:,:,:,0]))
print("t2[:,:,:3:2,0] = \n {}".format(t2[:,:,:3:2,0]))
print("t2[:,:,2,0] = \n {}".format(t2[:,:,2,0]))
print("t2[4,0,:,:] = \n {}".format(t2[4,0,:,:]))

### Advanced indexing

Using tensor with Boolean values to index data in tensor.
Advance indexing **is not supported in tensors containing names**.

In [ ]:
t3 = t2.rename(None)
target_indices = torch.tensor([False, False, True, True, True])
print(type(target_indices))
print(t3[target_indices])

In [ ]:
target_indices2 = torch.tensor([True, True, False, False])
print(type(target_indices2))
t4 = t3[:, target_indices2]
print("t4.shape = {}".format(t4.shape))
print(t4)
t4[0,0,0,0] = 101
print("t4 = {}".format(t4))
print("t3 = {}".format(t3))

In [ ]:
t4 = t3[target_indices, target_indices2]

In [ ]:
target_indices = t3 > 0
target_indices[0:2,:,:,:] = False
target_indices[:,2:4,:,:] = False
t4 = t3[target_indices]
print("t4.shape = {}".format(t4.shape))
print("t4 = {}".format(t4))
t4 = t4.view(-1,2,3,2)
print("\nafter view()")
print("t4.shape = {}".format(t4.shape))
print("t4 = {}".format(t4))

## Named tensor

In [ ]:
print("t2.float().mean(-3) = {}".format(t2.float().mean(-3)))
print("t2.float().mean('C')= {}".format(t2.float().mean('C')))

### Broadcasting 

In [ ]:
weights = torch.tensor([0.5, 0.3, 0.2, 0.1])
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
print(unsqueezed_weights.shape)
t2_weights = t2 * unsqueezed_weights
t2_weighted_sum = t2.sum(-3)
print(t2_weighted_sum)

In [ ]:
weights = torch.tensor([0.5, 0.3, 0.2, 0.1], names=['C'])
weights_aligned = weights.align_as(t2)
t2_weights = t2 * unsqueezed_weights
t2_weighted_sum = t2.sum('C')
print(t2_weighted_sum)

Let's normalize per channel

In [ ]:
(t2 - t2.float().mean('C').align_as(t2)) / (t2.float().std('C').align_as(t2) + 1e-6)

## The tensor API
All tensor operations can be divided into following groups:
* Cration operations — functions for constructing a tensor (e.g. ones, zeros ...).
* Random sampling — Functions for generating values by drawing randomly from probability distributions (e.g. randn, normal, ...).
* Serialization — Functions for saving and loading tensors (e.g load and save).
* Indexing, slicing, joining, mutating operations — Functions for changing the shape, stride, or content of a tensor (e.g. transpose, view, ...).
* Math operations — 
    * Elementwise operations — Functions for obtaining a new tensor by applying a function to each element independently (e.g abs, cos, ...).
    * Aggregation operations — Functions for computing aggregate values by iterating through tensors (e.g. mean, std, norm).
    * Comparison operations — Functions for evaluating numerical predicates over tensors (e.g. equal, max, ...).
    * Spectral operations — Functions for transforming in and operating in the frequency domain (e.g. stft, hamming_window, ...).
    * BLAS and LAPAC operations — Functions following the Basic Linear Algebra Subprograms (BLAS) and Linear Algebra Package (LAPAC) specification for scalar, vector-vector, matrix-vector, and matrix-matrix operations (e.g. svd, qr, ...).
    * Other operations — Functions operating on vectors or matrices (e.g. cross, trace, ...).
* Parallelism — Functions for controlling the number of threads for parallel CPU execution (e.g. set_num_threads, ...).

More details in http://pytorch.org/docs/stable/torch.html#tensors

## Tensor - storage
<img src="./figures/tensor_storage.PNG" alt="tensor_storage.PNG" width="550">

In [ ]:
print("t = {}".format(t))
print("t.storage() = {}".format(t.storage()))

In [ ]:
print("t.size() = {}".format(t.size()))
t_stride = t.stride()
print("t.stride() = {}".format(t_stride))
print("t.storage_offset() = {}".format(t.storage_offset()))

```t[i,j,k] = t.storage_offset() + i * t.stride[0] + j * t.stride[1] + k * t.stride[2] ```

In [ ]:
print("t[1,2,1] = {}".format(t[1, 2, 1]))
print("position in storage = {}".format(t[1, 2, 1].storage_offset()))
position = t.storage_offset() + 1 * t_stride[0] + 2 * t_stride[1] + 1 * t_stride[2]
print("position by formula = {}".format(position))
print("t[1,2,1] value in storage = {}".format(t.storage()[position]))

What happens if we do transpose?

In [ ]:
tt = t.transpose(0, 2)
print("tt.size() = {}".format(tt.size()))
tt_stride = tt.stride()
print("tt.stride() = {}".format(tt_stride))
print("tt.storage_offset() = {}".format(tt.storage_offset()))

In [ ]:
t.storage().data_ptr() == tt.storage().data_ptr()

In [ ]:
t.is_contiguous()

In [ ]:
tt.is_contiguous()

In [ ]:
tt = tt.contiguous()
print("tt.size() = {}".format(tt.size()))
tt_stride = tt.stride()
print("tt.stride() = {}".format(tt_stride))
print("tt.storage_offset() = {}".format(tt.storage_offset()))

In [ ]:
t.storage().data_ptr() == tt.storage().data_ptr()

## Moving tensors to the GPU

In [ ]:
m2 = torch.tensor([[11, 9], [7, 5], [22, 9]], device='cuda', dtype=torch.float32)

In [ ]:
torch.matmul(m.float().transpose(0, 1), m2)

In [ ]:
torch.matmul(m.to(device='cuda', dtype=torch.float32).transpose(0, 1), m2)

In [ ]:
torch.matmul(m.to(dtype=torch.float32).transpose(0, 1), m2.cpu())

## Pytorch tensor and NumPy array

Conversion is possible if a tensor is on CPU

In [ ]:
m_np = m.numpy()
print(type(m_np))
m2_np = m2.numpy()

In [ ]:
m2_np = m2.cpu().numpy()
print(type(m2_np))

In [ ]:
m3 = torch.from_numpy(m2_np)
print(type(m3))
print(m3)

## Save and load tensors

In [ ]:
torch.save(t, './my_t_a.t')

In [ ]:
with open('./my_t_b.t','wb') as f:
   torch.save(t, f)

In [ ]:
tx_a = torch.load('./my_t_b.t')

In [ ]:
with open('./my_t_a.t','rb') as f:
   tx_b = torch.load(f)

In [ ]:
print("t = {}".format(t))
print("tx_a = {}".format(tx_a))
print("tx_b = {}".format(tx_b))

### Tensor interoperability - HDF5

In [ ]:
import h5py

f = h5py.File('./t.hdf5', 'w')
dset = f.create_dataset('t_ex', data=t.numpy())
f.close()

In [ ]:
f = h5py.File('./t.hdf5', 'r')
dset = f['t_ex']
t_copy = torch.from_numpy(dset[:])
f.close()
print("t = {}".format(t))
print("t_copy = {}".format(t_copy))